### ISSUE TITLE
Aurelia js question

### ISSUE THREAD

**Issue by b-barry** [stampit-org/stampit#187]
Hello,

I am currently using Aurelia js and I am wondering if Stampit will work to replace the "Class components" of Aurelia js ?

Thanks your for your response.

**Comment by koresar** [comment]
@b-barry I tried hard to find Aurelia code samples. :) No luck.
Can you provide few link on the "Class components" you've mentioned?

**Comment by b-barry** [comment]
Hello,

You can use the aurelia skeleton below :

https://github.com/aurelia/skeleton-navigation

In Aurelia, we use also class like React and I am wondering if there is a library like stampit React for Aurelia.

**Comment by koresar** [comment]
I am not aware of "stampit React for Aurelia".

Looking at this code
https://github.com/aurelia/dependency-injection/blob/master/src/container.js#L83
I thnk that stampit v2 won't work with Aurelia. Simply because stampit discourages using the `new` keyword.
However, for interoperability sake I believe stampit v3 would need to support the `new` keyword. People could easily use stamps in the same places they use classes. This means that more people would use stampit. @ericelliott I think have to add the `new` keyword support to stampit v3. It's beneficial for stampit wider usage.

**Comment by b-barry** [comment]
Thank You for the quick answer.
I am looking forward stampit v3.

**Comment by koresar** [comment]
@b-barry looks like stamps can be easily used as a drop-in replacement of classes. The `new Stamp()` works as expected - creating a new object.

Although, I have never tried that. You could the first. Try it.

**Comment by b-barry** [comment]
@koresar Interesting, I will check it with the Aurelia skeleton
