### ISSUE TITLE
Simplify the overcomplicated parts of the stamp ecosystem

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#221]
@FredyC brought few valid points [here](https://github.com/stampit-org/stamp-utils/pull/8#discussion_r69393402). Quoting:
> To me personally it's super confusing to have a same name of a function with different behavior. I already said it with stampit, but having X different implementations of compose seems like a way to unmaintainable hell in my opinion. Call me lazy, but I think this is a bad decision.

> Just think of a new user coming to stamps which are already mind blowing on its own. That user has to face decision what module to pick: stamp-specification, stampit or stamp-utils? Studying what are differences and what he might actually need. I believe that for such innovative approach, the entry should be as smooth as possible.

> I think that eventually there should be just single most performant implementation of a compose and ideally any helper functions could be made as a separate module (I really like babel plugins way).

I fully agree with all statements. Having such a diversity of tools delays the stampit v3 release (I spread my time across too many activities, modules, and repositories). We unnecessarily overcomplicated the stamp ecosystem.

To improve the situation I propose to do the following steps (feel free to adjust my vision):
* Create a new super-performant pure `compose` implementation module (I parked name [stampx](https://www.npmjs.com/package/stampx) for us). It should contain no shortcut functions, statics, infections or else. It should prioritise performance over distribution size. And then:
  * Deprecate the `stamp-specification` NPM module for production use
  * Recommend the new module as the people's default `compose` implementation
  * Reuse the new module in `stampit`
* Make stampit a multi-export module. It should: 
  * export main stampit function as `export default function stampit() {`. It's the "infected compose" function.
  * export utility functions as ES6 exports - `export function init() {`
    * the utility functions should not add any statics or configuration, they should not infect either
  * export same utility functions as `stampit/init` files, like lodash (for people worrying about too large bundle sizes)
  * export the pure compose as ES6 and `stampit/compose`
* temporary stop development of `stamp-utils`, but bring it back when stamps get more traction and the need in the module increases

Also, I'll try producing the `Fun with stamps` series covering all the things mentioned above.

**Comment by ericelliott** [comment]
Why not use stamp-utils as the home for the core utilities like `compose()` and `init()`, then have stampit consume those? Extras can go in stampx, which could stand for "stamp extras".

I have already discussed removing the export from the stamp specification. It never should have had an export to begin with.

**Comment by koresar** [comment]
There are few complications here.

Stampit adds multiple new static methods to each stamp it generates (like `.props()` or `.methods()`, etc). So, people would expect:
```js
import {init} from 'stampit';
init(() => {}).props // MUST EXIST
init(() => {}).props({foo: 'bar'});
```

 `stamp-utils` does not (and should not) do that.
```js
import {init} from 'stamp-utils';
init(() => {}).props // must NOT exist
```

Moreover, it's better stampit to not depend on a module which can be re-implemented in 45 characters: `const init = f => compose({initializers: [f]})`

Also, @ericelliott please reread the quoted.
> Just think of a new user coming to stamps which are already mind blowing on its own. That user has to face decision what module to pick: stamp-specification, stampit or stamp-utils? Studying what are differences and what he might actually need.

You are correct saying that `stamp-specification` better not be a module. Also, Daniel is correct saying that user's better not be faced with the choice: "stampit or stamp-utils?"

**Comment by ericelliott** [comment]
> Daniel is correct saying that user's better not be faced with the choice: "stampit or stamp-utils?"

This part I disagree with. We have agreed since we decided to create the more functional micro-library functions that stampit is for people who want the convenience of the original chaining API.  I think that's easy to explain. And your suggestion would have the same problem anyway, except they'd be faced with "stampx or stampit?" instead.

I still feel quite strongly that putting the core utilities in stamp-utils and extras in stampx would be a lot less confusing. Consider also that I've already started using stamp-utils for core functions in blog posts and in my book, and if you change the location now, it creates a lot of work for me -- and as far as I can see, creates zero benefit. =)

**Comment by ericelliott** [comment]
The way I see it:

* **stamp-specification** = *specification only, NO EXPORTS*
* **stamp-utils** = *core utilities only (compose, init, isStamp, etc...)*
* **stampx** = eXtra (but still commonly used) utilities.. stuff you might write about in your stamp articles
* **stampit** = *original stamp chaining API + chain-enhanced utils*

**Comment by FredyC** [comment]
I like would propose rather different approach. First we shall use scoped modules in NPM. Then we can have like `@stamp/specification` along with `@stamp/compose` package with universal and most performant implementation of a core idea which will be reused in all other packages. Those other packages can be then split by some common idea, eg `@stamp/chain` (currently stampit) or `@stamp/check` (isStamp, isComposable) and `@stamp/classes` (eg. convertConstructor) and finally also `@stamp/react`.

Let's avoid using names like `utils`. It's terrible generic name that doesn't say anything specific about its uses. It feels like dumpster full of things that could not fit anywhere else.

I think it's really important for people learning about stamps to know where to begin. Which package to grab to start using it. Don't burden them with a choice of various packages right from the beginning.

Also Fun with Stamps articles should be focused around `compose` only and stop referencing `stamp-utils` randomly. Instead there should could be article for these helper modules explaining what they bring on the table in comparison to core `compose`.

**Comment by ericelliott** [comment]
@FredyC - what you're suggesting would deprecate a lot of existing code in a lot of software not controlled by us. It would also invalidate a lot of existing documentation.

What are the benefits? What would we gain by doing that? I'm all for micro-libraries, but none of the stamp libraries are large enough to warrant breaking them into a bunch of even tinier pieces. This isn't Lodash, or jQuery, or React. All of compose is less than 100 LOC. Many utilities (like `init()`) are literally one-liners.

You're suggesting that we create tens of thousands of hours of work for people so we can split some one-liners into their own modules?

**Comment by ericelliott** [comment]
EVERY TIME we make a breaking change to our libraries, we create LOTS OF WORK that real people must do (quite a bit for me, personally). The work is multiplied by every use of our libraries.

You really need to make a STRONG CASE for that work. Put another way programmers bill time at $50-$250/hour, and thousands of apps depend on stampit and other stamp APIs.

Imagine each necessary change takes 30 minutes and there are 3,000 changes required. Imagine the average hourly cost is $100/hour. ((30 * 3000)/60) * 100 = $150,000.

It's super easy to spend other people's money, but just imagine that you had to pay for the changes. Is it worth the cost?

**Comment by FredyC** [comment]
Well if you want to relate it to money, then why do you actually create and maintain stamps? It has surely cost you some dollars too. I don't agree with recalculating it like that. Open source is not about money, it's a journey how to make things better, not about sticking to couple of bad decisions because of some strange fear of change.

Nobody is talking about deleting those packages and forcing people to rewrite. Those packages can be alive for quite some time, but for sake of new projects, maintainability and less painful entry, there could slowly emerge what I've suggested to have a solid foundations for something amazing.

**Comment by koresar** [comment]
I feel we're going to have a good outcome from this conversation. I agree to both of you to some extent.

* @FredyC is right. We need a performant implementation of `compose`. Anywhere. Any new or existing module is fine to me. Maybe not today, but some day we would definitely need that.
* @ericelliott is right too. `stampit` is a trademark already. We should maintain it as long as we can.
> **stampit** = original stamp chaining API + chain-enhanced utils

However,
* The idea to have all these `@stamp/*` modules/repos is great but requires a lot of effort. I welcome anyone to do it. (I've just parked and started paying for the npm private user [~stamp](https://www.npmjs.com/~stamp) to make scoped modules a thing.)
* At this point I don't see why we need that "stampx" at all. I made a mistake reserving that module. Let's forget about it existence please. :) Sorry about bringing it up.

I'd resume:
* Eric would continue to work on `stamp-utils`.
* I'd continue to work on `stampit`.
* Someone might start creating micromodules at `@stamp/`.

EVERYBODY HAPPY! DANCE! :)
<img src="http://media.tumblr.com/tumblr_leni8yBSvN1qc5rs0.gif" />

**Comment by FredyC** [comment]
Completely agree @koresar, that's very good way to go for sure. Eventually it could even be like having those scoped modules together with `stampit` which would essentially have those scoped ones as dependencies to create a full package for head start. Then when people will understand what they need, they can create their own "bundle" of micro packages.

**Comment by FredyC** [comment]
By the way, for those scoped modules, we certainly don't need multiple repos. I would go the way [Babel makes it's plugins](https://github.com/babel/babel/tree/master/packages). They even extracted that functionality as a reusable module [lerna](https://github.com/lerna/lerna). And here is some [reasoning](https://github.com/babel/babel/blob/master/doc/design/monorepo.md) with cons/pros.

**Comment by ericelliott** [comment]
So the current plan is:

* **stamp-specification** = *specification only, NO EXPORTS*
* **stamp-utils** = *core utilities only (compose, init, isStamp, etc...)*
* **stampit** = *original stamp chaining API + chain-enhanced utils*
* **@stamp/modules** = *misc.. microlibrary modules*

Frankly, I don't really see the point of splitting `compose()` and `init()` into their own tiny microlibraries. As I mentioned before, `compose()` is less than 100 lines of actual code, and `init()` is literally a one-liner with a direct dependency on `compose()`, but if you guys insist that they be in their own microlibraries, I'm happy to aggregate those in `stamp-utils`.

**Comment by koresar** [comment]
I support the plan. It's good.

I have no strong feelings about that `init` being a micromodule. We'll see how it goes.

Now, let's try answering the question:
* How we can ease newcomers' choice on which library to use? What should we recommend?

**Comment by FredyC** [comment]
@ericelliott Point of spliting `compose` is to have a single most performant implementation that can be shared and reused. I said it many times, trying to keep multiple copies it maintenance hell.

Nobody said that `init` should be in a single package, that's definitely too much. Goal is to have only single `init` not like now same function with different functionality, that surely confuses people.

> How we can ease newcomers' choice on which library to use? What should we recommend?

I would surely speak about `stampit` as a main module. It will be full featured with everything that is needed to start with it. It can reference specification for sure. Also `stamp-specification` could back reference `stampit`, but nobody is going to find spec first before module I suppose.

What we need the most is definitely documentation and meaningful examples. I believe those examples should be in some codepen so they can be executed and played with. We could also have one official codepen playground with updated `stampit`.

Possibly we should also create small static website. People tend to use modules that are presented nicely instead of just bunch of MD files.

**Comment by FredyC** [comment]
@ericelliott We are going more likely with mono repo, so everything will be in a single repo just published to separate packages. One liners were already separated in `stampit`, so there isn't much of difference except that they can be reused, especially `isStamp` and `isComposable` instead of redefining those all over different packages.

**Comment by ericelliott** [comment]
Mono repo is fine.

**Comment by koresar** [comment]
The mono repo was created: https://github.com/stampit-org/stamp
All the unanswered questions, planning, and discussions should be moved there.

Feel free to reopen this issue if there are more to discuss.

Closing.
