### ISSUE TITLE
Functions stored by `props` get converted to an object

### ISSUE THREAD

**Issue by hoschi** [stampit-org/stampit#223]
I want to use a prop in my stamp code, so it can be easily changed when creating the stamp. But functions in props get converted to an object it seems. With `ref` it works as expected.
```
import stampit from 'stampit';

MyStamp = stampit({
    props:{
        transformRequestData:(data, context) => data
    }
});

let s = TransformRequestData.create();
let data = ['a'];
let context = {};
console.log(s.transformRequestData, typeof s.transformRequestData);
// {}, 'object'
s.transformRequestData(data, context);
// Error: transformRequestData is not a function
```

**Comment by koresar** [comment]
Thank @hoschi for taking this issue here.

Yeah. It's just bad API naming. In stampit v2 `props` are deeply cloned/merged. Whereas `refs` are object references.

I'd recommend using stampit v3. It has this problem solved, `props` and `refs` are the same thing.

To install stampit v3 run `npm i stampit@rc`. It's pretty stable. Just lacks some documentation atm.

Feel free to post any other questions in the gitter chat: https://gitter.im/stampit-org/stampit
People are pretty fast responding there.

Cheers

**Comment by hoschi** [comment]
I can't upgrade to a RC version at the moment, if this is fixed in your eyes, you can close this issue.
