### ISSUE TITLE
Supporting IE11

### ISSUE THREAD

**Issue by koresar** [stampit-org/stampit#243]
IE11 does not have [Object.assign](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign). Thus, stampit v3 won't run properly there without a polyfil.

We should:
1) Run our tests on node 0.12 since it has no Object.assign too.
2) Make sure the tests run (add a polyfil or ponyfil to our test build).
3) Warn people in the README that the polyfil is required.

**Comment by FredyC** [comment]
I would go with warning on this since it's a single browser and adding polyfill is very easy with service https://cdn.polyfill.io/v2/polyfill.js. Enabling tests for 0.12 doesn't seem about right because it is missing also whole bunch of other ES6 features and would bring only issues. Also I would like to remind your your #224 once again, you keep forgetting about it ;)

**Comment by koresar** [comment]
Will be fixed with #251
