### ISSUE TITLE
Recommended approach for private data

### ISSUE THREAD

**Issue by far-blue** [stampit-org/stampit#311]
Hi :)

Is the recommended approach for private data to create a closure that returns an object with the methods you want, which you execute and pass to .methods() or the methods: property and within which you hold private vars?

e.g.

```
let Foo = stampit.compose({
  methods: function () {
    let privateVar = 'baa';
    return {
      getPrivateVar () {
        return privateVar;
      }
    }
  }()
})
```

Or is there a neater way?

**Comment by koresar** [comment]
Yeah, there is a neater way. :)

There is a whole new ecosystem of stamps - https://www.npmjs.com/~stamp
One of them is https://www.npmjs.com/package/@stamp/privatize

It was first introduced in [Fun with stamps. Episode 12](https://medium.com/@koresar/fun-with-stamps-episode-12-new-stamp-home-582cc198086). But it's more like Java "protected", rather than "private".
The [Episode 13](https://medium.com/@koresar/fun-with-stamps-episode-13-method-collision-control-d34ec0c8cc8d) explains how to make it more private.

If you have any questions regarding the `@stamp/privatize` I'd recommend asking about them here - https://github.com/stampit-org/stamp

There are few other ways to privatize properties in JS:
* closure inside an initializer
* [WeakMap](http://mdn.io/WeakMap)
* [Symbol](http://mdn.io/Symbol)

See your question answered here - https://github.com/stampit-org/stampit/issues/229

**Comment by koresar** [comment]
A new stamp was developed - https://www.npmjs.com/package/@stamp/privatize
This is how it works:
```js
import Privatize from '@stamp/privatize';

let accessPassword, accessSetPassword;
const Original = compose({
  properties: {password: '123'},
  methods: {
    setPassword(value) { this.password = value; },
    checkAccess() {
      accessPassword = this.password;
      accessSetPassword = this.setPassword;
    }
  }
});
 
// Add Privatize behavior, additionally protect the 'setPassword' method  
const Stamp = Original.compose(Privatize).privatizeMethods('setPassword');
 
// All properties and the method 'setPassword' are undefined 
const instance = Stamp();
expect(instance.password).toBeUndefined();
expect(instance.setPassword).toBeUndefined();
 
// But the 'checkAccess' method have access to the properties and 'setPassword' 
instance.checkAccess();
expect(accessPassword).toBe('123');
expect(accessSetPassword).toBe(Original.compose.methods.setPassword);
```

**Comment by far-blue** [comment]
that's great, thanks :) I'm starting to understand how all the bits fit together now!

**Comment by koresar** [comment]
amazing! :)
I myself learning how to educate people properly about stamps. your example is vivid.
So, thank you!

**Comment by ericelliott** [comment]
I use closures in init functions for data privacy in stamps and functional mixins in general. It is the technique I recommend, and I find it much cleaner than `privatize`.

**Comment by FredyC** [comment]
Just want to share a neat way of adding methods within initializer. 

```js
compose({
  init(opts, { stamp }) {
     const { myPrivateVar } = stamp.compose.configuration
     Object.assign(this, {
       myMethod() { return myPrivateVar + opts.passedVar }
     })
  }
})
```

I am thinking that it would be lovely being able to avoid the use of `Object.assign`, but keeping the simplicity of the solution. For example returning an object that gets assigned to the instance. Otherwise, if you want a method to have its proper display name, you have to do `this.myMethod = function myMethod()` or `const myMythod = () => {}` followed by `this.myMethod = myMethod`. Going simply with ˙this.myMethod = () => {}˙ doesn't work.

It could be an actual candidate for a stamp specification grow. It's not possible to provide such solution with a stamp, am I right?

**Comment by koresar** [comment]
Stampit v1 had the `extend` (aka `Object.assign`) method inbuilt - `stampit.extend`. It's main purpose was exactly as your code describes @FredyC.

**Comment by FredyC** [comment]
@koresar I am not sure how that's relevant. It's surely great there was some possibly simlar feature, but it's not there now. Can you express your opinion on the idea instead? :)

**Comment by ericelliott** [comment]
Hi @FredyC -- I'm not sure what you're getting at. JavaScript already supplies shortcuts for object composition, which is why we removed `extend`. Consider this form, coming soon to the JS spec. This already works in babel:

```js
init((
  {passedVar},
  { instance, stamp }
) => {
  const { myPrivateVar } = stamp.compose.configuration;
  return {
    ...instance,
    ...{
      myMethod() { return myPrivateVar + opts.passedVar }
    }
  };
});
```

**Comment by koresar** [comment]
Oh! I think I get it!!! @FredyC please supply code examples next time. :)
But I think this is what you are thinking of:
```js
const Stamp = stampit({
  init: function () {
    return { bar: 1 }; // THIS OVERWRITE OBJECT ATM
  },
  methods: {
    foo() {}
  }
});

const obj = Stamp();

assert(Object.getPrototypeOf(obj) === Stamp.compose.methods);
assert(typeof obj.foo === 'function');
assert(obj.bar === 1);
```

That would be a breaking change to the specification. How many people would benefit form that?

**Comment by FredyC** [comment]
Ok I guess that @ericelliott comment is closer to what I meant. Although I am not sure that using `...instance` is good idea because some people may be using eg. Symbols a with this it would be lost.

```js
compose({
  privates(opts, { stamp }) {
     const { myPrivateVar } = stamp.compose.configuration
     return {
       myMethod() { return myPrivateVar + opts.passedVar }
     }
  }
})
```

It's the same signature as initializer, but different name (WIP) so it can used only to return new methods that should be added to the stamp. It's just an idea, probably not that critical.

**Comment by koresar** [comment]
@FredyC JFYI. The `...instance` is a shortcut of `Object.assign()`. And it copies both string properties and symbol properties. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

**Comment by FredyC** [comment]
Ah ok, wasn't aware of that. I still don't particularly like this feature of returning a different instance object, but I see that you don't like my idea, so let's forget about it :)

**Comment by ericelliott** [comment]
We could non-destructively pass an `extend` utility fixed to the instance into init functions (which are basically functional mixins.... then you could do:

```js
init((
  {passedVar},
  { instance, stamp, extend }
) => {
  const { myPrivateVar } = stamp.compose.configuration;
  return extend({
    myMethod() { return myPrivateVar + opts.passedVar }
  });
});
```
It would be trivial to define the fixed extend like this:

```js
const extend = curry(Object.assign)(instance);
```

We could use lodash curry, or:

```js
const curry = (
  f, arr = []
) => (...args) => (
  a => a.length === f.length ?
    f(...a) :
    curry(f, a)
)([...arr, ...args]);
```

**Comment by FredyC** [comment]
@ericelliott That actually sounds like a good idea. Actually wouldn't it be nicer if stamps would allow customizing that second object that's passed into initializer? That way we could add this functionality as another composable stamp instead of hard coding there. I am not sure how to call that yet, but it could be similar to `configuration` and deep merged there when an instance is created.

**Comment by ericelliott** [comment]
Stamps really shouldn't be depending on the existence of other stamps. If you have to mix a stamp in to get `extend` passed in, you introduce an implicit dependency on that stamp for every stamp that uses `extend`.

I'm really not sure this feature is needed, considering that `{...instance, new: stuff}}` is already on the standards track. IMO, best practice should be to favor this going forward. Which means that stamps should not count on extending an existing object, because other stamps may be returning a completely new object. =)

**Comment by koresar** [comment]
>  Actually wouldn't it be nicer if stamps would allow customizing that second object that's passed into initializer?

it's already there. Called "configuration". Just use `stamp.compose.configuration` for all the new stuff.

```js
init((
  {passedVar},
  { instance, stamp }
) => {
  const { myPrivateVar, extend } = stamp.compose.configuration;
  return extend(instance, {
    myMethod() { return myPrivateVar + opts.passedVar }
  });
});
```
