### ISSUE TITLE
TypeError·Object expected in combineProperties in IE11

### ISSUE THREAD

**Issue by kellypacker** [stampit-org/stampit#316]
Getting this error only in IE11 (not Chrome or Firefox). [Live example](https://www.fisherguiding.com/fishing-guide/lucky-lady-fishing-charters). I tried to track down the cause, but got a bit lost. I can try to create a standalone example of this, but wanted to also check and see if this rings any bells with someone who knows the library. Thanks for any help.

**Comment by koresar** [comment]
@kellypacker could you please provide:
1) version of the stampit
2) full stack trace.

**Comment by FredyC** [comment]
@kellypacker Please see the [install section](https://github.com/stampit-org/stampit#install) in readme, especially that warning there :) This is actually what's your problem there.

@koresar It's coming from here: https://github.com/stampit-org/stampit/blob/master/src/utils.js#L41 because `Object.assign` is not defined :) I think we should add a warning to `stamp/core` about this just to avoid these weird errors.

**Comment by kellypacker** [comment]
@FredyC ah, I missed that. That was the issue. Thank you for the response!

**Comment by koresar** [comment]
@kellypacker As of v3.2.0 stampit do not need polyfils. Works in IE11 out of the box. :)
