### ISSUE TITLE
array in props persist across instances of stamp

### ISSUE THREAD

**Issue by ilan-deepreach** [stampit-org/stampit#349]
```
var stampit = require("stampit")

var b = stampit({props: {a: []}, init() {console.log(this.a);this.a.push(1); console.log(this.a)}})
b();
b();
b();
```

what's logged is [1] then [1, 1] then [1, 1, 1]
I expect [1] consistently. Why would props be shared between objects that are instance of stamps.

**Comment by koresar** [comment]
Hello. This is by design.

To solve your problem you can create that array array time for every new object instance.
```
stampit({
  init() {
    this.a = [];
  }
});
```

Or, better, in this case use the `deepProps`:

```
stampit({
  deepProps: []
});
```

The `props` are always [copied by reference](https://stampit.js.org/api/properties#descriptor-merging-algorithm). That's by design. (Same as in classes.)

Whereas the `deepProps` are always (deeply) [cloned](https://stampit.js.org/api/deep-properties#descriptor-merging-algorithm).
